<?php

namespace Ideasoft\Providers;

use Ideasoft\Console\Command\MigrationsCommand;
use Illuminate\Support\ServiceProvider;

class IdeasoftServiceProvider extends ServiceProvider
{

    public function boot()
    {
        $this->mergeConfigFrom(__DIR__ . '/../../config/database.php', "database.connections.ideasoft");
        if ($this->app->runningInConsole()) {
            $this->commands(
                commands: [
                    MigrationsCommand::class,
                ],
            );
        }
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
